### PR TITLE
Feature/mcmc tracking

### PR DESCRIPTION
**Pull request by dellaert**
Updated old pair coding branch on MCMC tracking with what I could. I moved two new factors into their own compilation units, but unfortunately `SwitchingBetweenFactor` no longer compiles, and I think I need some @marcrasi  help :-)

### CODE REVIEW

**Comment by dabrahams** [comment]
@dellaert Are you still working on this, and do you need our help?

**Comment by dellaert** [comment]
Yes, thanks ! Maybe I should merge in develop and check what the current error is?

**Comment by dellaert** [comment]
So, looking for latest dev snapshot on https://github.com/tensorflow/swift/blob/master/Installation.md, I notice there is none for XCode 11. Will XCode 11 June 16 do?

**Comment by marcrasi** [comment]
Yeah, that should still work. We haven't made any backwards incompatible changes recently.

**Comment by dellaert** [comment]
@marcrasi @dabrahams I merged in master and tried compiling again, and output is below. I think at one point @marcrasi made it possible to be only differentiable with respect to *some* of the variables, but maybe this is now done in a different way? In this case, we have a *discrete* variable indicating the motion model, so obviously we can't be differentiable with respect to that:

```
/Users/dellaert/git/SwiftFusion/Sources/SwiftFusion/Inference/SwitchingBetweenFactor.swift:54:36: error: type 'SwitchingBetweenFactor<Pose, JacobianRows>.ErrorVector' (aka 'Pose.TangentVector') does not conform to protocol 'ScalarsInitializableVector'
  public typealias Linearization = JacobianFactor<JacobianRows, ErrorVector>
                                   ^
/Users/dellaert/git/SwiftFusion/Sources/SwiftFusion/Inference/SwitchingBetweenFactor.swift:16:15: error: type 'Int' does not conform to protocol 'Differentiable'
public struct SwitchingBetweenFactor<Pose: LieGroup, JacobianRows: FixedSizeArray>:
              ^
/Users/dellaert/git/SwiftFusion/Sources/SwiftFusion/Inference/SwitchingBetweenFactor.swift:16:15: error: 'LinearizableFactor' requires that 'Int' conform to 'Differentiable'
public struct SwitchingBetweenFactor<Pose: LieGroup, JacobianRows: FixedSizeArray>:
              ^
/Users/dellaert/git/SwiftFusion/Sources/SwiftFusion/Inference/SwitchingBetweenFactor.swift:16:15: note: requirement specified as 'Int' : 'Differentiable'
public struct SwitchingBetweenFactor<Pose: LieGroup, JacobianRows: FixedSizeArray>:
              ^
/Users/dellaert/git/SwiftFusion/Sources/SwiftFusion/Inference/SwitchingBetweenFactor.swift:16:15: note: requirement from conditional conformance of 'Tuple2<Int, Pose>' (aka 'Tuple<Int, Tuple<Pose, Empty>>') to 'DifferentiableVariableTuple'
public struct SwitchingBetweenFactor<Pose: LieGroup, JacobianRows: FixedSizeArray>:
              ^
/Users/dellaert/git/SwiftFusion/Sources/SwiftFusion/Inference/SwitchingBetweenFactor.swift:16:15: note: requirement from conditional conformance of 'SwitchingBetweenFactor<Pose, JacobianRows>.Variables' (aka 'Tuple<Pose, Tuple<Int, Tuple<Pose, Empty>>>') to 'DifferentiableVariableTuple'
public struct SwitchingBetweenFactor<Pose: LieGroup, JacobianRows: FixedSizeArray>:
              ^
/Users/dellaert/git/SwiftFusion/Sources/SwiftFusion/Inference/SwitchingBetweenFactor.swift:16:15: error: type 'SwitchingBetweenFactor<Pose, JacobianRows>' does not conform to protocol 'LinearizableFactor'
public struct SwitchingBetweenFactor<Pose: LieGroup, JacobianRows: FixedSizeArray>:
              ^
/Users/dellaert/git/SwiftFusion/Sources/SwiftFusion/Inference/SwitchingBetweenFactor.swift:50:15: note: candidate is missing attribute '@differentiable(wrt: x)'
  public func errorVector(at x: Variables) -> Pose.TangentVector {
              ^
         @differentiable(wrt: x) 
/Users/dellaert/git/SwiftFusion/Sources/SwiftFusion/Inference/Factor.swift:56:8: note: protocol requires function 'errorVector(at:)' with type '(SwitchingBetweenFactor<Pose, JacobianRows>.Variables) -> SwitchingBetweenFactor<Pose, JacobianRows>.ErrorVector'
  func errorVector(at x: Variables) -> ErrorVector
```

**Comment by marcrasi** [comment]
Yes, now it's done in a different way. There is a method for returning the linearizable component a factor. Here is an example implementation of this method: https://github.com/borglab/SwiftFusion/blob/b1ea710d76ac605479e60fb37602334f68503147/Tests/SwiftFusionTests/Inference/FactorTests.swift#L36

That example is a switching motion model factor so you should be able to almost copy and paste it in to yours. Let me know if you want me to help by adding a commit to this PR that makes it use the new way.

**Comment by dellaert** [comment]
OK, I fixed the compile issues based on that example. Thanks !

**Comment by ProfFan** [comment]
@dellaert Is this ready 4 merging?

**Comment by dellaert** [comment]
Yes. Not a fully fledged tracker yet but unit tests pass so let’s do it

**Comment by ProfFan** [comment]
@dellaert Can you merge master and merge this PR?

**Comment by dellaert** [comment]
Merged in branch from #180, need to resolve that first.

**Pull request merged**
