### PR TITLE
Tracking Mega PR

### PR DESCRIPTION
**Pull request by ProfFan**

### CODE REVIEW

**Comment by dellaert** [comment]
Are we committing straight into this branch? I thought -at leas Fan suggested this to me - that we considered it a “develop” like thing, updated with PRs. Not sure how I feel abandoning good practice close to a deadline :-)

**Comment by ProfFan** [comment]
@dellaert  Sorry I forgot to switch branch last night... Just reset and I'll do a PR

**Comment by ProfFan** [comment]
Will merge once the CI passes.

**Comment by dellaert** [comment]
Nice, Will try soon!

**Pull request merged**
