### PR TITLE
higher resolution bee video

### PR DESCRIPTION
**Pull request by marcrasi**
I downloaded one (4-second) bee video and annotated 2 (slow moving, not waggling) bees in it.

This PR adds code for loading the data.

This PR also includes the simple annotation tool that I wrote to do the annotations.

Here is an example notebook that displays the data: https://colab.sandbox.google.com/drive/1M2MRDNWGufFbamZlo3d0dZM-OV5CgE0E#scrollTo=me1CsMBYDm8P

### CODE REVIEW

**Comment by ProfFan** [comment]
Wow, let me check on this!

**Comment by ProfFan** [comment]
@marcrasi Appears that the bboxs are in different orientation than the old ones?

image

**Comment by marcrasi** [comment]
Yeah. It shouldn't really affect anything. I can flip them around to be consistent with the older ones though.

**Comment by marcrasi** [comment]
I have adjusted the orientation to match the other bee bounding boxes.

**Review by ProfFan — APPROVED** [review]
Awesome!

**Pull request merged**
