### PR TITLE
add g2o reader and Pose2SLAMG2O example

### PR DESCRIPTION
**Pull request by marcrasi**
Adds a `G2OReader` (with tests), and a "Pose2SLAMG2O" example binary that loads a g2o file into a factor graph and runs inference on it.

My purpose is to get some end to end nontrivial amount of computation running, so that I can start benchmarking and profiling things. The PR achieves this, even though it's missing some pieces that https://github.com/borglab/gtsam/blob/develop/examples/Pose2SLAMExample_g2o.cpp has. I have noted in the file comment what pieces are missing, so that we can fill them in later.

Resolves https://github.com/borglab/SwiftFusion/issues/39.

(Note, this is a PR into feature/nonlinear_factor_graph, because it depends on that feature. I took the liberty of copying feature/nonlinear_factor_graph from @ProfFan's repo to this repo so that I could create this PR. Let me know if that bothers you and I won't do it again.)

### CODE REVIEW

**Comment by ProfFan** [comment]
Oh great! I'll review shortly

**Comment by ProfFan** [comment]
Also, @dan-zheng any idea when will https://bugs.swift.org/browse/TF-1234 be in the nightly?

**Comment by dan-zheng** [comment]
> Also, @dan-zheng any idea when will https://bugs.swift.org/browse/TF-1234 be in the nightly?

Would you like a macOS or Linux toolchain?

I need to debug something about the nightly macOS toolchain, but I can give you a custom macOS toolchain with a fix for TF-1234 in a few hours.

**Comment by ProfFan** [comment]
@dan-zheng That's really nice :) Thanks in advance!

**Comment by marcrasi** [comment]
> (I am not sure the current optimization thing would work tho, should be fine with like 20 poses)

I ran this on the INTEL dataset (1228 poses) from https://lucacarlone.mit.edu/datasets/ and it seems to behave reasonably! The error decreases each iteration. The iterations are really slow though. I'm going to investigate the performance soon.

**Comment by dan-zheng** [comment]
> Also, @dan-zheng any idea when will https://bugs.swift.org/browse/TF-1234 be in the nightly?

Here's a newer macOS toolchain: https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-PATCH-2020-05-07-a-osx.pkg

Could you please try it to see if [TF-1234](https://bugs.swift.org/browse/TF-1234) is fixed?

**Comment by ProfFan** [comment]
@dan-zheng There seems to be another (different) segfault:
```
Assertion failed: (conformances.size() == numConformanceRequirements), function Storage, file /Users/swiftninjas/s4tf/swift/lib/AST/SubstitutionMap.cpp, line 46.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-05-07-a.xctoolchain/usr/bin/swift -frontend -c /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Core/AnyDifferentiable.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Core/DataTypes.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Core/Dictionary+Differentiable.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Core/Jacobian.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Core/LieGroup.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Core/Manifold.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Core/MathUtil.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Core/StandardBasis.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Core/TensorConvertible.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Core/Vector.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Geometry/Pose2.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Geometry/Pose3.swift -primary-file /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Geometry/Rot2.swift -primary-file /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Geometry/Rot3.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Inference/BetweenFactor.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Inference/Errors.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Inference/Factor.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Inference/GaussianFactorGraph.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Inference/JacobianFactor.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Inference/NonlinearFactorGraph.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Inference/PriorFactor.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Inference/Values.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Inference/VectorValues.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Optimizers/CGLS.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Optimizers/NLCG.swift /Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion/Sources/SwiftFusion/Optimizers/SGD.swift -emit-module-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot2~partial.swiftmodule -emit-module-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot3~partial.swiftmodule -emit-module-doc-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot2~partial.swiftdoc -emit-module-doc-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot3~partial.swiftdoc -emit-module-source-info-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot2~partial.swiftsourceinfo -emit-module-source-info-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot3~partial.swiftsourceinfo -serialize-diagnostics-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot2.dia -serialize-diagnostics-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot3.dia -emit-dependencies-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot2.d -emit-dependencies-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot3.d -emit-reference-dependencies-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot2.swiftdeps -emit-reference-dependencies-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot3.swiftdeps -target x86_64-apple-macos10.14 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Products/Debug -F /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -enable-testing -g -module-cache-path /Users/proffan/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -enable-anonymous-context-mangled-names -Xcc -I/Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/swift-overrides.hmap -Xcc -I/Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Products/Debug/include -Xcc -I/Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/DerivedSources-normal/x86_64 -Xcc -I/Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/DerivedSources/x86_64 -Xcc -I/Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/DerivedSources -Xcc -DSWIFT_PACKAGE=1 -Xcc -DDEBUG=1 -Xcc -working-directory/Users/proffan/Projects/Development/CV/SLAM/SwiftFusion/SwiftFusion -target-sdk-version 10.15.4 -module-name SwiftFusion -o /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot2.o -o /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/x86_64/Rot3.o -index-store-path /Users/proffan/Library/Developer/Xcode/DerivedData/SwiftFusion-hefhlxocwhzdzbbphhmqtrwamujk/Index/DataStore -index-system-modules 
1.	Swift version 5.3-dev (LLVM 613d6deaef, Swift 747ca11869)
2.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { Guaranteed Passes } on SIL for SwiftFusion.SwiftFusion)
3.	While running pass #861 SILModuleTransform "Differentiation".
4.	While processing // differentiability witness for Matrix3Coordinate.init(_:_:_:_:_:_:_:_:_:)
sil_differentiability_witness [serialized] [parameters 0 1 2 3 4 5 6 7 8] [results 0] @$s11SwiftFusion17Matrix3CoordinateVyACSd_S8dtcfC : $@convention(method) (Double, Double, Double, Double, Double, Double, Double, Double, Double, @thin Matrix3Coordinate.Type) -> @owned Matrix3Coordinate {
}

```

**Comment by ProfFan** [comment]
@dan-zheng The code is in branch `feature/nlfg_with_manifold` , BTW

**Comment by dan-zheng** [comment]
I wasn't able to reproduce the compiler crash from `feature/nlfg_with_manifold` ([`e42c2c71617f409fc42f63c476f72ecac5370624`](https://github.com/borglab/SwiftFusion/tree/e42c2c71617f409fc42f63c476f72ecac5370624)). Instead, I got some compilation errors:

<details>
<p>

```
$ swift build
/Users/danielzheng/SwiftFusion/Sources/SwiftFusion/Inference/BetweenFactor.swift:73:18: error: expression is not differentiable
    return error.tensor.squared().sum().scalars[0]
                 ^
/Users/danielzheng/SwiftFusion/Sources/SwiftFusion/Inference/BetweenFactor.swift:73:18: note: member is not differentiable because the corresponding protocol requirement is not '@differentiable'
    return error.tensor.squared().sum().scalars[0]
                 ^
/Users/danielzheng/SwiftFusion/Sources/SwiftFusion/Inference/PriorFactor.swift:53:21: error: expression is not differentiable
    let error = val.local(difference)
                    ^
/Users/danielzheng/SwiftFusion/Sources/SwiftFusion/Inference/PriorFactor.swift:53:21: note: member is differentiable only with respect to a smaller subset of arguments
    let error = val.local(difference)
                    ^
/Users/danielzheng/SwiftFusion/Sources/SwiftFusion/Inference/PriorFactor.swift:46:26: error: expression is not differentiable
    let residual = error.tensor.squared().sum().scalars[0]
                         ^
/Users/danielzheng/SwiftFusion/Sources/SwiftFusion/Inference/PriorFactor.swift:46:26: note: member is not differentiable because the corresponding protocol requirement is not '@differentiable'
    let residual = error.tensor.squared().sum().scalars[0]
                         ^
/Users/danielzheng/SwiftFusion/Sources/SwiftFusion/Inference/PriorFactor.swift:44:48: error: expression is not differentiable
    let error = values[keys[0]].baseAs(T.self).local(difference)
                                               ^
/Users/danielzheng/SwiftFusion/Sources/SwiftFusion/Inference/PriorFactor.swift:44:48: note: member is differentiable only with respect to a smaller subset of arguments
    let error = values[keys[0]].baseAs(T.self).local(difference)
                                               ^
[25/26] Compiling SwiftFusion Rot3.swift
```

</p>
</details>

Could you please check whether you're building from the same commit, no local changes?

**Comment by ProfFan** [comment]
@dan-zheng You can try building from XCode, I think the reason why it's not showing up is that SwiftPM stops at the first error, while XCode does compile for every file even one of them fails.

**Comment by ProfFan** [comment]
Also, I think the error "Member is differentiable only with respect to a smaller subset of arguments" (described in TF-1234) is still there.

**Comment by marcrasi** [comment]
I took over investigating this one. Still trying to figure out what's going on, but I did come up with a workaround if you want to be quickly unblocked: https://github.com/borglab/SwiftFusion/pull/43

**Pull request merged**
