### PR TITLE
run the factor graph on VOT videos

### PR DESCRIPTION
**Pull request by marcrasi**
This runs the appearance factor tracking graph pipeline on VOT videos, in a very simple "naive" way as a starting point.

First we scale all the patches in a VOT video to 100x100 and then we train the RAE on those patches.

Then we create the tracking factor graph and initializing it with the initial bounding box.

The factor graph does not yet know how to change the size of patches over time, but this is a feature that would be pretty straightforward to add.

Also it's "forbidden" to train using the tracking labels before trying to infer the tracking labels, but it's an easy way to make sure things are working.

It doesn't work very well yet. I haven't debugged it very much. Here's a notebook showing what it does: https://colab.sandbox.google.com/drive/16t-lAqMk4nFh35P9CeGX8TYfdkuLCYHy#scrollTo=5lRJaU9pw7Ee

And I made a lot of changes without documenting them yet, so that is also TODO.

### CODE REVIEW

**Comment by ProfFan** [comment]
We should try without RAE (Raw L2 distance) first as a baseline. Also, can use some of the functions in `RAE Tracking Graph` to do a roundtrip comparison of encoded objects.

**Comment by marcrasi** [comment]
I think I just found a serious bug while trying some of your suggestions. The tracker might not be so bad after I fix it :)

**Comment by dellaert** [comment]
Cool, finding bugs is always good :-) Just requested access to notebook.

**Comment by marcrasi** [comment]
I just did some pair coding with Fan, and we got a raw pixel tracker working. It works surprisingly well on some of the datasets. We needed to do a trick with initialization. It's in the notebook, which is currently very messy.

I'll now work on cleaning all this up and making a simple function that takes (dataset, tracking_strategy) and returns an inferred track and metrics. This will let us make a nice table of how the different tracking strategies do, and it'll let us see how changes improve things.

I expect that the trick with initialization might also help the RAE tracker, so I'll try that after I have the nice table that lets us quantify things.

**Comment by marcrasi** [comment]
I have updated the code and the notebook to run tracking on multiple videos and calculate the frame where tracking first fails (which I have defined as center >10 pixels from the ground truth).

You can see the full code in the notebook and in this PR. It's pretty messy and requires more cleanup but I tried to document the important parts.

The results for the raw pixel tracker are:
```
["ball1": Optional(30), "ants3": Optional(6), "ants1": Optional(27), "fish2": Optional(3), "fish1": nil, "fish3": Optional(11), "ball2": Optional(1)]
```
(A value means that it fails on that frame. A nil means that it does not fail for the entire 50 frames that I tested on.)

The RAE tracker fails almost instantly on any video that I try it on, so I suspect that it's still bugged. It requires more debugging, which I'll work on tomorrow.

**Comment by dellaert** [comment]
More debugging or more unit tests :-) ?
On a separate note: could you give notebook access to my dellaert@gmail.com rather than my google.com address?

**Comment by marcrasi** [comment]
I have updated this with more doc comments and simplifications. I haven't gotten it working on mac yet, but that's what I'm trying to do next.

**Comment by dellaert** [comment]
Penguin also seems to not work with latest XCode and S4TF Dev Snapshot:

```
Build target PenguinTesting with configuration Debug

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'PenguinTesting' from project 'Penguin')
    cd /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/SourcePackages/checkouts/penguin
    export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
    export TOOLCHAINS\=com.google.swift.20200916\ 
    /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-09-16-a.xctoolchain/usr/bin/swiftc -incremental -module-name PenguinTesting -Onone -enable-batch-mode -enforce-exclusivity\=checked @/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/Objects-normal/x86_64/PenguinTesting.o.SwiftFileList -DSWIFT_PACKAGE -DDEBUG -DXcode -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -target x86_64-apple-macos10.10 -g -module-cache-path /Users/dellaert/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Index/DataStore -swift-version 5 -I /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -parse-as-library -c -j8 -output-file-map /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/Objects-normal/x86_64/PenguinTesting-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/Objects-normal/x86_64/PenguinTesting.swiftmodule -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/swift-overrides.hmap -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Products/Debug/include -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/DerivedSources-normal/x86_64 -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/DerivedSources/x86_64 -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -emit-objc-header -emit-objc-header-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/Objects-normal/x86_64/PenguinTesting-Swift.h -Xcc -working-directory/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/SourcePackages/checkouts/penguin

CompileSwift normal x86_64 /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/SourcePackages/checkouts/penguin/Sources/PenguinTesting/StdlibProtocolTests.swift (in target 'PenguinTesting' from project 'Penguin')
    cd /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/SourcePackages/checkouts/penguin
    /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-09-16-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/SourcePackages/checkouts/penguin/Sources/PenguinTesting/StdlibProtocolTests.swift -emit-module-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/Objects-normal/x86_64/StdlibProtocolTests\~partial.swiftmodule -emit-module-doc-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/Objects-normal/x86_64/StdlibProtocolTests\~partial.swiftdoc -emit-module-source-info-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/Objects-normal/x86_64/StdlibProtocolTests\~partial.swiftsourceinfo -serialize-diagnostics-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/Objects-normal/x86_64/StdlibProtocolTests.dia -emit-dependencies-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/Objects-normal/x86_64/StdlibProtocolTests.d -emit-reference-dependencies-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/Objects-normal/x86_64/StdlibProtocolTests.swiftdeps -target x86_64-apple-macos10.10 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -enable-testing -g -module-cache-path /Users/dellaert/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -enable-anonymous-context-mangled-names -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/swift-overrides.hmap -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Products/Debug/include -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/DerivedSources-normal/x86_64 -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/DerivedSources/x86_64 -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -Xcc -working-directory/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/SourcePackages/checkouts/penguin -target-sdk-version 10.15.6 -parse-as-library -module-name PenguinTesting -o /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/Penguin.build/Debug/PenguinTesting.build/Objects-normal/x86_64/StdlibProtocolTests.o -index-store-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Index/DataStore -index-system-modules

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/swift/AppKit.swiftmodule/x86_64.swiftinterface:7:8: error: no such module '_SwiftAppKitOverlayShims'
import _SwiftAppKitOverlayShims
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/swift/AppKit.swiftmodule/x86_64.swiftinterface:1:1: error: failed to build module 'AppKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.2 (swiftlang-1103.8.25.8 clang-1103.0.30.20)', may have used features that aren't supported by this compiler, 'Swift version 5.3-dev (LLVM 14a10d635b229fb, Swift c08d0804e2e44ac)'
// swift-interface-format-version: 1.0
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/swift/AppKit.swiftmodule/x86_64.swiftinterface:7:8: error: no such module '_SwiftAppKitOverlayShims'
import _SwiftAppKitOverlayShims
       ^
/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/SourcePackages/checkouts/penguin/Sources/PenguinTesting/StdlibProtocolTests.swift:15:8: error: failed to build module 'XCTest' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Swift version 5.3-dev (LLVM 14a10d635b229fb, Swift c08d0804e2e44ac)'
import XCTest
       ^
```

**Comment by dellaert** [comment]
Aha! @ProfFan reminded me of the fix: use XCode beta

**Comment by dellaert** [comment]
FYI All tests now run for me on Mac and Xavier NX (except 1, unrelated to this PR, will create an issue)

**Comment by ProfFan** [comment]
WIP have a tracker with raw L2 distance.

**Review by dellaert — COMMENTED** [review]
Very cool! Will let Fan review and approve, as I am out of cycles and a bit far removed from this code at this point. I learned about parseable commands which is cool :-)

**Review by ProfFan — APPROVED** [review]

**Pull request merged**
