### PR TITLE
covectors and differentiable vectors

### PR DESCRIPTION
**Pull request by marcrasi**
This adds differentiability to the vector abstractions in https://github.com/borglab/SwiftFusion/pull/70.

We need covectors to define pullbacks of vector space operations, so I also added covectors.

### CODE REVIEW

**Comment by dellaert** [comment]
All checks failed? :-)

**Comment by ProfFan** [comment]
@dellaert Looks like a GitHub issue, I restarted the build

**Comment by ProfFan** [comment]
@dellaert Test is successful

**Comment by marcrasi** [comment]
Closing because this turned out not to be important for the initial generic factor graph work. We should revisit eventually.

**Pull request closed without merging**
